= Yu Hong Herald - Project Portfolio
:imagesDir: ../images
:stylesDir: ../stylesheets

== PROJECT: Car Servicing Manager

---

== Overview

Coming in v2.0

== Summary of contributions

* *Major enhancement*: added *the ability to import job entries from an excel file*
** What it does: allows the user to undo all previous commands one at a time. Preceding undo commands can be reversed by using the redo command.
** Justification: This feature improves the product significantly because a user can make mistakes in commands and the app should provide a convenient way to rectify them.
** Highlights: This enhancement affects existing commands and commands to be added in future. It required an in-depth analysis of design alternatives. The implementation too was challenging as it required changes to existing commands.
** Credits: _{mention here if you reused any code/ideas from elsewhere or if a third-party library is heavily used in the feature so that a reader can make a more accurate judgement of how much effort went into the feature}_

* *Minor enhancement*: added a set command that allows the user to use a custom keyword in place of the default keyword.

* *Code contributed*: [https://github.com[Functional code]] [https://github.com[Test code]] _{give links to collated code files}_

* *Other contributions*:

** Project management:
*** Helped to edit PRs for merging for v1.2- (Pull requests https://github.com[#40], https://github.com[#48])
** Enhancements to existing features:
*** Added JobListPanel to support displaying jobs (Pull requests https://github.com[#53])
** Documentation:
** Community:
** Tools:

_{you can add/remove categories in the list above}_

== Contributions to the User Guide

|===
|_Given below are sections I contributed to the User Guide. They showcase my ability to write documentation targeting end-users._
|===

include::../UserGuide.adoc[tag=set]

include::../UserGuide.adoc[tag=importexport]

== Contributions to the Developer Guide

|===
|_Given below are sections I contributed to the Developer Guide. They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
|===

include::../DeveloperGuide.adoc[tag=set]

include::../DeveloperGuide.adoc[tag=importexport]

